### ISSUE TITLE
BroadcastReceiver components are not allowed to bind to services

### ISSUE THREAD

**Issue by UnumInAgro** [mayzs/paho.mqtt.android#1]
android.content.ReceiverCallNotAllowedException: BroadcastReceiver components are not allowed to bind to services
                                                                                                    	at android.app.ReceiverRestrictedContext.bindService(ContextImpl.java:124)
                                                                                                    	at org.eclipse.paho.android.service.MqttAndroidClient.connect(MqttAndroidClient.java:436)

**Comment by mayzs** [comment]
使用最新版  1.1.5
